import type { CSSProperties } from 'react'

export const dashboardStyles: Record<string, CSSProperties> = {
  appContainer: {
    display: 'grid',
    gridTemplateColumns: '320px minmax(0, 1fr) 380px',
    width: '100%',
    minHeight: '100vh',
    overflow: 'hidden',
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
    backgroundColor: '#F4F3F0',
    color: '#000000',
    fontSize: '14px',
    WebkitFontSmoothing: 'antialiased',
  },
  column: {
    display: 'flex',
    flexDirection: 'column',
    borderRight: '1px solid #000000',
    minHeight: '100vh',
    overflowY: 'auto',
    backgroundColor: '#F4F3F0',
  },
  columnLast: {
    display: 'flex',
    flexDirection: 'column',
    minHeight: '100vh',
    overflowY: 'auto',
    backgroundColor: '#F4F3F0',
  },
  viewHeader: {
    padding: '16px 20px',
    borderBottom: '1px solid #000000',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    position: 'sticky',
    top: 0,
    backgroundColor: '#F4F3F0',
    zIndex: 10,
  },
  viewTitle: {
    fontSize: '11px',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
  },
  iconBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: '4px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#000000',
  },
  sectionLabel: {
    fontSize: '12px',
    fontWeight: 600,
    padding: '20px 20px 12px',
  },
  categoryGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '16px',
    padding: '0 20px 20px',
    borderBottom: '1px solid #D1D1D1',
  },
  categoryItem: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '6px',
    cursor: 'pointer',
    position: 'relative',
    textAlign: 'center',
  },
  abstractIcon: {
    width: '56px',
    height: '56px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  categoryLabel: {
    fontSize: '11px',
    color: '#888888',
    transition: 'color 0.2s ease',
  },
  categoryLabelActive: {
    fontSize: '11px',
    color: '#000000',
    fontWeight: 500,
  },
  categoryCount: {
    fontSize: '10px',
    color: '#888888',
  },
  iconBg: {
    position: 'absolute',
    width: '80px',
    height: '80px',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    opacity: 0,
    transition: 'opacity 0.3s ease',
    zIndex: 1,
    filter: 'blur(12px)',
  },
  searchBar: {
    padding: '12px 20px',
    borderBottom: '1px solid #000000',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  searchInput: {
    flex: 1,
    background: 'none',
    border: 'none',
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
    fontSize: '14px',
    outline: 'none',
    color: '#000000',
  },
  infoBar: {
    padding: '10px 20px',
    borderBottom: '1px solid #D1D1D1',
    display: 'flex',
    justifyContent: 'space-between',
    gap: '12px',
    alignItems: 'center',
    color: '#666666',
    fontSize: '12px',
  },
  bookmarkList: {
    display: 'flex',
    flexDirection: 'column',
  },
  bookmarkItem: {
    display: 'flex',
    padding: '20px',
    borderBottom: '1px solid #000000',
    gap: '16px',
    color: 'inherit',
    cursor: 'pointer',
    backgroundColor: 'transparent',
    transition: 'background-color 0.2s',
  },
  authorAvatar: {
    width: '48px',
    height: '48px',
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 700,
    fontSize: '14px',
    border: '1px solid #000000',
  },
  tweetContentWrapper: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  tweetHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    gap: '12px',
  },
  authorName: {
    fontWeight: 600,
    fontSize: '14px',
  },
  authorHandle: {
    color: '#888888',
    fontSize: '13px',
    marginLeft: '6px',
  },
  tweetMeta: {
    fontSize: '12px',
    color: '#888888',
  },
  tweetText: {
    fontSize: '14px',
    lineHeight: 1.5,
    color: '#000000',
  },
  tweetActions: {
    display: 'flex',
    gap: '12px',
    flexWrap: 'wrap',
    marginTop: '2px',
  },
  actionStat: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    fontSize: '12px',
    color: '#666666',
    border: '1px solid #000000',
    padding: '3px 8px',
    borderRadius: '999px',
  },
  itemTag: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '28px',
    height: '28px',
    border: '1px solid #000000',
    marginTop: '2px',
  },
  analysisSection: {
    padding: '20px',
    borderBottom: '1px solid #000000',
  },
  segmentControl: {
    display: 'flex',
    border: '1px solid #000000',
    borderRadius: '20px',
    overflow: 'hidden',
    marginBottom: '24px',
  },
  segmentBtn: {
    flex: 1,
    background: 'none',
    border: 'none',
    padding: '8px 0',
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
    fontSize: '12px',
    fontWeight: 500,
    color: '#000000',
    cursor: 'pointer',
    borderRight: '1px solid #000000',
    transition: 'all 0.2s',
  },
  segmentBtnActive: {
    flex: 1,
    border: 'none',
    padding: '8px 0',
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
    fontSize: '12px',
    fontWeight: 500,
    cursor: 'pointer',
    borderRight: '1px solid #000000',
    transition: 'all 0.2s',
    backgroundColor: '#000000',
    color: '#F4F3F0',
  },
  segmentBtnLast: {
    flex: 1,
    background: 'none',
    border: 'none',
    padding: '8px 0',
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
    fontSize: '12px',
    fontWeight: 500,
    color: '#000000',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  segmentBtnLastActive: {
    flex: 1,
    border: 'none',
    padding: '8px 0',
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
    fontSize: '12px',
    fontWeight: 500,
    cursor: 'pointer',
    transition: 'all 0.2s',
    backgroundColor: '#000000',
    color: '#F4F3F0',
  },
  chartContainer: {
    width: '100%',
    height: '200px',
    position: 'relative',
    marginBottom: '16px',
  },
  chartGrid: {
    position: 'absolute',
    inset: 0,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    pointerEvents: 'none',
  },
  chartGridLine: {
    borderBottom: '1px dashed #888888',
    width: '100%',
  },
  chartSvg: {
    width: '100%',
    height: '100%',
    position: 'relative',
    zIndex: 2,
    overflow: 'visible',
  },
  insightText: {
    fontSize: '13px',
    lineHeight: 1.5,
    color: '#666666',
  },
  tagList: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
    padding: '0 20px 20px',
  },
  tagPill: {
    border: '1px solid #000000',
    padding: '4px 12px',
    borderRadius: '16px',
    fontSize: '12px',
    cursor: 'pointer',
    backgroundColor: 'transparent',
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
    color: '#000000',
  },
  tagPillActive: {
    border: '1px solid #000000',
    padding: '4px 12px',
    borderRadius: '16px',
    fontSize: '12px',
    cursor: 'pointer',
    backgroundColor: '#000000',
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
    color: '#F4F3F0',
  },
  actionRow: {
    display: 'flex',
    gap: '8px',
    padding: '0 20px 16px',
    flexWrap: 'wrap',
  },
  primaryButton: {
    border: '1px solid #000000',
    backgroundColor: '#000000',
    color: '#F4F3F0',
    padding: '9px 12px',
    fontSize: '12px',
    cursor: 'pointer',
    fontWeight: 600,
  },
  secondaryButton: {
    border: '1px solid #000000',
    backgroundColor: 'transparent',
    color: '#000000',
    padding: '9px 12px',
    fontSize: '12px',
    cursor: 'pointer',
    fontWeight: 500,
  },
  statusBox: {
    margin: '0 20px 16px',
    padding: '12px',
    border: '1px solid #000000',
    fontSize: '12px',
    lineHeight: 1.5,
    color: '#666666',
  },
  compactInput: {
    margin: '0 20px 10px',
    width: 'calc(100% - 40px)',
    border: '1px solid #000000',
    backgroundColor: 'transparent',
    padding: '10px 12px',
    fontSize: '12px',
    outline: 'none',
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
  },
  helperText: {
    fontSize: '12px',
    color: '#666666',
    padding: '0 20px 16px',
    lineHeight: 1.5,
  },
  detailCard: {
    border: '1px solid #000000',
    padding: '14px',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  detailMeta: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
  },
  detailLabel: {
    fontSize: '11px',
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    color: '#666666',
  },
  detailBody: {
    fontSize: '14px',
    lineHeight: 1.6,
  },
  detailSelect: {
    width: '100%',
    border: '1px solid #000000',
    backgroundColor: 'transparent',
    padding: '10px 12px',
    fontSize: '12px',
    outline: 'none',
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
  },
  sourceList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  sourceRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottom: '1px dashed #D1D1D1',
    paddingBottom: '8px',
  },
  sourceHandle: {
    fontWeight: 500,
    fontSize: '13px',
  },
  sourceCount: {
    color: '#888888',
    fontSize: '13px',
  },
  emptyState: {
    padding: '28px 20px',
    color: '#666666',
    fontSize: '13px',
    lineHeight: 1.6,
  },
}
